//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoPagoConnector.OperationsService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.wso2.org/dataservice")]
    public partial class DataServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string current_paramsField;
        
        private string current_request_nameField;
        
        private string nested_exceptionField;
        
        private DataServiceFaultSource_data_service source_data_serviceField;
        
        private string ds_codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string current_params {
            get {
                return this.current_paramsField;
            }
            set {
                this.current_paramsField = value;
                this.RaisePropertyChanged("current_params");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string current_request_name {
            get {
                return this.current_request_nameField;
            }
            set {
                this.current_request_nameField = value;
                this.RaisePropertyChanged("current_request_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nested_exception {
            get {
                return this.nested_exceptionField;
            }
            set {
                this.nested_exceptionField = value;
                this.RaisePropertyChanged("nested_exception");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DataServiceFaultSource_data_service source_data_service {
            get {
                return this.source_data_serviceField;
            }
            set {
                this.source_data_serviceField = value;
                this.RaisePropertyChanged("source_data_service");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ds_code {
            get {
                return this.ds_codeField;
            }
            set {
                this.ds_codeField = value;
                this.RaisePropertyChanged("ds_code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.wso2.org/dataservice")]
    public partial class DataServiceFaultSource_data_service : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string locationField;
        
        private string default_namespaceField;
        
        private string descriptionField;
        
        private string data_service_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string default_namespace {
            get {
                return this.default_namespaceField;
            }
            set {
                this.default_namespaceField = value;
                this.RaisePropertyChanged("default_namespace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string data_service_name {
            get {
                return this.data_service_nameField;
            }
            set {
                this.data_service_nameField = value;
                this.RaisePropertyChanged("data_service_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.todopago.com.ar")]
    public partial class Operations : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rESULTCODEField;
        
        private string rESULTMESSAGEField;
        
        private System.Nullable<System.DateTime> dATETIMEField;
        
        private string oPERATIONIDField;
        
        private string cURRENCYCODEField;
        
        private System.Nullable<float> aMOUNTField;
        
        private string tYPEField;
        
        private string iNSTALLMENTPAYMENTSField;
        
        private string cUSTOMEREMAILField;
        
        private string iDENTIFICATIONTYPEField;
        
        private string iDENTIFICATIONField;
        
        private string cARDNUMBERField;
        
        private string cARDHOLDERNAMEField;
        
        private string tICKETNUMBERField;
        
        private string aUTHORIZATIONCODEField;
        
        private string bARCODEField;
        
        private string cOUPONEXPDATEField;
        
        private string cOUPONSECEXPDATEField;
        
        private string cOUPONSUBSCRIBERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string RESULTCODE {
            get {
                return this.rESULTCODEField;
            }
            set {
                this.rESULTCODEField = value;
                this.RaisePropertyChanged("RESULTCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string RESULTMESSAGE {
            get {
                return this.rESULTMESSAGEField;
            }
            set {
                this.rESULTMESSAGEField = value;
                this.RaisePropertyChanged("RESULTMESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> DATETIME {
            get {
                return this.dATETIMEField;
            }
            set {
                this.dATETIMEField = value;
                this.RaisePropertyChanged("DATETIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string OPERATIONID {
            get {
                return this.oPERATIONIDField;
            }
            set {
                this.oPERATIONIDField = value;
                this.RaisePropertyChanged("OPERATIONID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string CURRENCYCODE {
            get {
                return this.cURRENCYCODEField;
            }
            set {
                this.cURRENCYCODEField = value;
                this.RaisePropertyChanged("CURRENCYCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<float> AMOUNT {
            get {
                return this.aMOUNTField;
            }
            set {
                this.aMOUNTField = value;
                this.RaisePropertyChanged("AMOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string INSTALLMENTPAYMENTS {
            get {
                return this.iNSTALLMENTPAYMENTSField;
            }
            set {
                this.iNSTALLMENTPAYMENTSField = value;
                this.RaisePropertyChanged("INSTALLMENTPAYMENTS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string CUSTOMEREMAIL {
            get {
                return this.cUSTOMEREMAILField;
            }
            set {
                this.cUSTOMEREMAILField = value;
                this.RaisePropertyChanged("CUSTOMEREMAIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string IDENTIFICATIONTYPE {
            get {
                return this.iDENTIFICATIONTYPEField;
            }
            set {
                this.iDENTIFICATIONTYPEField = value;
                this.RaisePropertyChanged("IDENTIFICATIONTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string IDENTIFICATION {
            get {
                return this.iDENTIFICATIONField;
            }
            set {
                this.iDENTIFICATIONField = value;
                this.RaisePropertyChanged("IDENTIFICATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string CARDNUMBER {
            get {
                return this.cARDNUMBERField;
            }
            set {
                this.cARDNUMBERField = value;
                this.RaisePropertyChanged("CARDNUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string CARDHOLDERNAME {
            get {
                return this.cARDHOLDERNAMEField;
            }
            set {
                this.cARDHOLDERNAMEField = value;
                this.RaisePropertyChanged("CARDHOLDERNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true, Order=13)]
        public string TICKETNUMBER {
            get {
                return this.tICKETNUMBERField;
            }
            set {
                this.tICKETNUMBERField = value;
                this.RaisePropertyChanged("TICKETNUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string AUTHORIZATIONCODE {
            get {
                return this.aUTHORIZATIONCODEField;
            }
            set {
                this.aUTHORIZATIONCODEField = value;
                this.RaisePropertyChanged("AUTHORIZATIONCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string BARCODE {
            get {
                return this.bARCODEField;
            }
            set {
                this.bARCODEField = value;
                this.RaisePropertyChanged("BARCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string COUPONEXPDATE {
            get {
                return this.cOUPONEXPDATEField;
            }
            set {
                this.cOUPONEXPDATEField = value;
                this.RaisePropertyChanged("COUPONEXPDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string COUPONSECEXPDATE {
            get {
                return this.cOUPONSECEXPDATEField;
            }
            set {
                this.cOUPONSECEXPDATEField = value;
                this.RaisePropertyChanged("COUPONSECEXPDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string COUPONSUBSCRIBER {
            get {
                return this.cOUPONSUBSCRIBERField;
            }
            set {
                this.cOUPONSUBSCRIBERField = value;
                this.RaisePropertyChanged("COUPONSUBSCRIBER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.todopago.com.ar", ConfigurationName="OperationsService.OperationsPortType")]
    public interface OperationsPortType {
        
        // CODEGEN: Generating message contract since the wrapper name (OperationsColections) of message GetByOperationIdResponse does not match the default value (GetByOperationId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetByOperationId", ReplyAction="urn:GetByOperationIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TodoPagoConnector.OperationsService.DataServiceFault), Action="urn:GetByOperationIdDataServiceFault", Name="DataServiceFault", Namespace="http://ws.wso2.org/dataservice")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TodoPagoConnector.OperationsService.GetByOperationIdResponse GetByOperationId(TodoPagoConnector.OperationsService.GetByOperationIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetByOperationId", WrapperNamespace="http://api.todopago.com.ar", IsWrapped=true)]
    public partial class GetByOperationIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.todopago.com.ar", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MERCHANT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.todopago.com.ar", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OPERATIONID;
        
        public GetByOperationIdRequest() {
        }
        
        public GetByOperationIdRequest(string MERCHANT, string OPERATIONID) {
            this.MERCHANT = MERCHANT;
            this.OPERATIONID = OPERATIONID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OperationsColections", WrapperNamespace="http://api.todopago.com.ar", IsWrapped=true)]
    public partial class GetByOperationIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.todopago.com.ar", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Operations")]
        public TodoPagoConnector.OperationsService.Operations[] Operations;
        
        public GetByOperationIdResponse() {
        }
        
        public GetByOperationIdResponse(TodoPagoConnector.OperationsService.Operations[] Operations) {
            this.Operations = Operations;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OperationsPortTypeChannel : TodoPagoConnector.OperationsService.OperationsPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperationsPortTypeClient : System.ServiceModel.ClientBase<TodoPagoConnector.OperationsService.OperationsPortType>, TodoPagoConnector.OperationsService.OperationsPortType {
        
        public OperationsPortTypeClient() {
        }
        
        public OperationsPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperationsPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationsPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationsPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TodoPagoConnector.OperationsService.GetByOperationIdResponse TodoPagoConnector.OperationsService.OperationsPortType.GetByOperationId(TodoPagoConnector.OperationsService.GetByOperationIdRequest request) {
            return base.Channel.GetByOperationId(request);
        }
        
        public TodoPagoConnector.OperationsService.Operations[] GetByOperationId(string MERCHANT, string OPERATIONID) {
            TodoPagoConnector.OperationsService.GetByOperationIdRequest inValue = new TodoPagoConnector.OperationsService.GetByOperationIdRequest();
            inValue.MERCHANT = MERCHANT;
            inValue.OPERATIONID = OPERATIONID;
            TodoPagoConnector.OperationsService.GetByOperationIdResponse retVal = ((TodoPagoConnector.OperationsService.OperationsPortType)(this)).GetByOperationId(inValue);
            return retVal.Operations;
        }
    }
}
